### ISSUE TITLE
Extend to multi-classification problem

### ISSUE THREAD

**Issue by pribadihcr** [furkanulger/SJI-entropy-reg#1]
Hi, Is the method can be extended to the multi-classification problem?. thanks

**Comment by furkanulger** [comment]
Thank you for the good question. I will work on this and provide an update, however, it can take some time.

**Comment by furkanulger** [comment]
I updated the code and added an optional parameter (num_classes) to train and test the models for multi-class classification. Type -h to get more information. Please let me know if you can validate it.

`
python skewed_JSdivergence.py -t train -m <model> -c <number_of_classes>(default:2) -a <skewness_value>(default:0.5) -lr <learning rate>(default:1e-4) -e <num_of_epochs>(default:150)
`
